apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  labels:
    purpose: infra
spec:
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: azure/ingress
    repoURL: https://github.com/carlosvillarroelin2/aks-platform-engineering
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true