apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  labels:
    purpose: marketplace
spec:
  destination:
    namespace: marketplace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: azure/marketplace/mongodb
    repoURL: https://github.com/carlosvillarroelin2/aks-platform-engineering
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true