apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: domesupport@in2.es
    preferredChain: ""
    privateKeySecretRef:
      name: lets-encrypt-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "dev.in2.es"
      http01:
        ingress:
          ingressClassName: nginx
